"""Shared LLM tier and value label handling for GitHub issue automation scripts.

AllotMint's AI-suggested issues are tagged with a "tier" label that names the
model best suited to implement them: ``local-7b``, ``local-14b``, ``haiku``,
``sonnet``, or ``opus`` (roughly ordered from "simple, mechanical" to
"complex, architectural"). Issue bodies generated by AI review tooling
include a "**LLM tier**" section naming one of these tiers; this module finds
that tier and maps it to the corresponding GitHub label.

Issues are also tagged with an independent "value" label -- ``Low Value``,
``Medium Value``, or ``High Value`` -- naming their impact/priority. Issue
bodies generated by AI review tooling include a "**Value**" section naming
one of these tiers; this module finds that value and maps it to the
corresponding GitHub label.

This module is stdlib-only so it can be imported by any script under
``.github/scripts`` (or other workflow tooling) without extra dependencies.
"""

from __future__ import annotations

import re

# Maps a recognised tier name to its GitHub label. Keys are matched
# case-insensitively against issue bodies and model name strings.
LLM_TIER_MAP: dict[str, str] = {
    "local-7b": "local-7b",
    "local-14b": "local-14b",
    "haiku": "haiku",
    "sonnet": "sonnet",
    "opus": "opus",
}

# Tier label used by get_fallback_tier_label() when a model string doesn't
# name any known tier. Sonnet is the mid-point of the tier scale, so it's the
# safest default when no signal is available.
_DEFAULT_TIER_LABEL = "sonnet"

# Additional model-size markers (e.g. "qwen2.5-14b-instruct") that imply a
# local-model tier even though the model string doesn't contain "local-*".
_SIZE_MARKER_TIERS: dict[str, str] = {
    "7b": "local-7b",
    "14b": "local-14b",
}


def _build_tier_pattern(tier_map: dict[str, str]) -> re.Pattern[str]:
    """Build a regex matching a "**LLM tier**" section naming one of tier_map's keys."""
    tiers = "|".join(re.escape(tier) for tier in tier_map)
    return re.compile(
        rf"\*\*LLM\s+tier\*\*[^\n]*\n[^\n]*\*\*({tiers})\b",
        re.IGNORECASE,
    )


def extract_tier_label(body: str, tier_map: dict[str, str] | None = None) -> str | None:
    """Return the tier label named in ``body``, or None if no tier is mentioned.

    Looks first for a "**LLM tier**" section naming a known tier, then falls
    back to a bare mention of a tier name anywhere in the body.
    """
    tier_map = LLM_TIER_MAP if tier_map is None else tier_map
    pattern = _build_tier_pattern(tier_map)
    m = pattern.search(body)
    if m:
        return tier_map.get(m.group(1).lower())
    for tier, label in tier_map.items():
        if re.search(rf"\b{re.escape(tier)}\b", body, re.IGNORECASE):
            return label
    return None


def get_fallback_tier_label(
    model_name: str,
    tier_map: dict[str, str] | None = None,
    size_marker_map: dict[str, str] | None = None,
) -> str:
    """Derive a tier label from a model name string (e.g. "claude-haiku-4-5-20251001").

    Used when a tier can't be extracted from issue body text but a model name
    is available. Returns ``_DEFAULT_TIER_LABEL`` if the model name doesn't
    name a known tier or size.

    Size-marker matching is skipped by default for custom tier_map callers
    unless they explicitly opt in via size_marker_map.
    """
    used_default_tier_map = tier_map is None
    tier_map = LLM_TIER_MAP if tier_map is None else tier_map
    model_lower = model_name.lower()
    for tier, label in tier_map.items():
        if tier in model_lower:
            return label

    if size_marker_map is None:
        size_marker_map = _SIZE_MARKER_TIERS if used_default_tier_map else {}

    for marker, label in size_marker_map.items():
        if label in tier_map.values() and re.search(rf"\b{marker}\b", model_lower):
            return label

    return _DEFAULT_TIER_LABEL


# Maps a recognised value word to its GitHub label. Keys are matched
# case-insensitively against issue bodies.
VALUE_LABEL_MAP: dict[str, str] = {
    "low": "Low Value",
    "medium": "Medium Value",
    "high": "High Value",
}

# Fallback value label when no value can be extracted from an issue body.
# AI-suggested issues have historically skewed low-value, so that's the
# safest default when no signal is available.
DEFAULT_VALUE_LABEL = "Low Value"


def _build_value_pattern(value_map: dict[str, str]) -> re.Pattern[str]:
    """Build a regex matching a "**Value**" section naming one of value_map's keys."""
    words = "|".join(re.escape(word) for word in value_map)
    return re.compile(
        rf"\*\*Value\*\*[^\n]*\n[^\n]*\*\*({words})\s+Value\b",
        re.IGNORECASE,
    )


def extract_value_label(body: str, value_map: dict[str, str] | None = None) -> str | None:
    """Return the value label named in ``body``, or None if no value is mentioned.

    Looks first for a "**Value**" section naming a known value word (e.g.
    "**High Value**"), then falls back to a bare "<word> Value" mention
    anywhere in the body.
    """
    value_map = VALUE_LABEL_MAP if value_map is None else value_map
    pattern = _build_value_pattern(value_map)
    m = pattern.search(body)
    if m:
        return value_map.get(m.group(1).lower())
    for word, label in value_map.items():
        if re.search(rf"\b{re.escape(word)}\s+Value\b", body, re.IGNORECASE):
            return label
    return None


def _cli(argv: list[str]) -> int:
    """CLI entry point so bash workflow steps can reuse the extraction logic
    above instead of re-implementing it with their own regexes.

    Usage: ``echo "$ISSUE_BODY" | python3 llm_labels.py value-label``
    Prints the extracted label, falling back to ``DEFAULT_VALUE_LABEL``.
    """
    import sys

    if len(argv) != 1 or argv[0] != "value-label":
        print("usage: llm_labels.py value-label < issue_body", file=sys.stderr)
        return 2
    body = sys.stdin.read()
    print(extract_value_label(body) or DEFAULT_VALUE_LABEL)
    return 0


if __name__ == "__main__":
    import sys

    raise SystemExit(_cli(sys.argv[1:]))
