from __future__ import annotations

"""Routes exposing trading agent functionality."""

from typing import List
import logging
import os

from fastapi import APIRouter

from backend import alerts as alert_utils
from backend.agent import trading_agent
from backend.agent.models import TradingSignal
from backend.common.alerts import publish_alert
from backend.config import config
from backend.utils.telegram_utils import send_message, redact_token

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/trading-agent", tags=["trading-agent"])


@router.get(
    "/signals",
    response_model=List[TradingSignal],
    response_model_exclude_none=True,
)
async def signals(
    notify_email: bool = False, notify_telegram: bool = False
) -> List[TradingSignal]:
    """Return trade signals generated by the trading agent.

    Each signal contains the ticker symbol, a ``BUY`` or ``SELL`` action and
    a human-readable reason describing why the signal was generated.
    Optional email and/or Telegram notifications can be triggered by setting
    the corresponding query parameters to ``true``.
    """

    raw_signals = trading_agent.run(notify=False)

    if raw_signals:
        messages = [
            f"{s['action']} {s['ticker']}: {s['reason']}" for s in raw_signals
        ]
        text = "\n".join(messages)
        if notify_email:
            try:
                publish_alert({"message": text})
                alert_utils.send_push_notification(text)
            except RuntimeError:
                logger.info("SNS topic ARN not configured; skipping email publish")
        if (
            notify_telegram
            and os.getenv("TELEGRAM_BOT_TOKEN")
            and os.getenv("TELEGRAM_CHAT_ID")
            and config.app_env != "aws"
        ):
            try:
                send_message(text)
            except Exception as exc:  # pragma: no cover - network errors
                logger.warning("Telegram send failed: %s", redact_token(str(exc)))

    return [TradingSignal.model_validate(sig) for sig in raw_signals]
