from __future__ import annotations

"""Routes exposing trading agent functionality."""

from fastapi import APIRouter

from backend.agent import trading_agent

router = APIRouter(prefix="/trading-agent", tags=["trading-agent"])


@router.get("/signals")
async def signals():
    """Return trade signals generated by the trading agent."""
    return trading_agent.run()
