from __future__ import annotations

"""Routes exposing trading agent functionality."""

from typing import List

from fastapi import APIRouter

from backend.agent import trading_agent
from backend.agent.models import TradingSignal

router = APIRouter(prefix="/trading-agent", tags=["trading-agent"])


@router.get("/signals", response_model=List[TradingSignal])
async def signals() -> List[TradingSignal]:
    """Return trade signals generated by the trading agent.

    Each signal contains the ticker symbol, a ``BUY`` or ``SELL`` action and
    a human-readable reason describing why the signal was generated.
    """

    raw_signals = trading_agent.run()
    return [TradingSignal.model_validate(sig) for sig in raw_signals]
