"""Backend application entry-point.

This module exposes :func:`create_app`, a small factory that builds and
configures the FastAPI instance used by both the local development server
(`uvicorn`) and the AWS Lambda handler. Keeping the setup in a function makes
it easy for tests to create isolated apps and mirrors the pattern recommended
by FastAPI.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.routes.instrument import router as instrument_router
from backend.routes.portfolio import router as portfolio_router
from backend.routes.timeseries_meta import router as timeseries_router
from backend.common.portfolio_utils import (
    refresh_snapshot_in_memory,
    refresh_snapshot_in_memory_from_timeseries,
)


def create_app() -> FastAPI:
    """Create and configure the FastAPI application.

    The function wires together middleware, registers routers and primes the
    in-memory price snapshot so the first request is quick. Returning the app
    instance instead of creating it at module import time keeps things
    test-friendly and avoids accidental state sharing between invocations.
    """

    # The FastAPI constructor accepts a few descriptive fields that end up in
    # the autogenerated OpenAPI/Swagger documentation.
    app = FastAPI(title="Allotmint API", version="1.0", docs_url="/docs")

    # ───────────────────────────── CORS ─────────────────────────────
    # During development the frontend often runs on a different origin. We
    # therefore allow every origin/method/header. A production deployment
    # should tighten these values.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ──────────────────────────── Routers ────────────────────────────
    # The API surface is composed of a few routers grouped by concern.
    # They are registered here on the main application instance.
    app.include_router(portfolio_router)
    app.include_router(instrument_router)
    app.include_router(timeseries_router)

    # ────────────────────── Health-check endpoint ─────────────────────
    @app.get("/health")
    async def health():
        """Return a small payload used by tests and uptime monitors."""

        return {"status": "ok"}

    # ─────────────── Warm the price snapshot on startup ───────────────
    @app.on_event("startup")
    async def _warm_snapshot():
        """Pre-fetch recent price data so the first request is fast."""

        refresh_snapshot_in_memory_from_timeseries(days=30)

    return app


# optional local test:  python -m backend.app
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(create_app(), host="0.0.0.0", port=8000)
