AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Allotmint backend Lambda

Parameters:
  AppEnv:
    Type: String
    Default: prod

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          APP_ENV: !Ref AppEnv
      Events:
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: backend/Dockerfile.lambda
      DockerContext: ../..
      DockerTag: latest
      DockerBuildArgs:
        APP_ENV: !Ref AppEnv

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
