/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

const CACHE_NAME = 'allotmint-cache-v1';
const CORE_ASSETS = ['/', '/index.html', '/manifest.webmanifest'];

// Precache the assets generated by the Vite build.
// self.__WB_MANIFEST is replaced at build time with the list of files to cache.
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(CORE_ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    ).then(() => self.clients.claim())
  );
});

// Runtime caching for same-origin GET requests not precached.
registerRoute(
  ({ request, url }) => request.method === 'GET' && url.origin === self.location.origin,
  new CacheFirst({ cacheName: CACHE_NAME })
);

self.addEventListener('push', (event: PushEvent) => {
  const payload = event.data?.text();
  let data: Record<string, unknown> = {};
  if (payload) {
    try {
      data = JSON.parse(payload);
    } catch {
      data = { body: payload };
    }
  }
  const title = typeof data.title === 'string' ? data.title : 'AllotMint';
  const options: NotificationOptions = {
    body: typeof data.body === 'string' ? data.body : ''
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  event.waitUntil(self.clients.openWindow('/'));
});

export {};
