export const tabPluginMap = {
  group: {},
  owner: {},
  instrument: {},
  performance: {},
  transactions: {},
  trading: {},
  screener: {},
  timeseries: {},
  watchlist: {},
  movers: {},
  instrumentadmin: {},
  dataadmin: {},
  virtual: {},
  support: {},
  settings: {},
  reports: {},
  scenario: {},
  logs: {},
};
export type TabPluginId = keyof typeof tabPluginMap;
export const orderedTabPlugins = [
  { id: "group", priority: 0 },
  { id: "movers", priority: 10 },
  { id: "instrument", priority: 20 },
  { id: "owner", priority: 30 },
  { id: "performance", priority: 40 },
  { id: "transactions", priority: 50 },
  { id: "trading", priority: 55 },
  { id: "screener", priority: 60 },
  { id: "timeseries", priority: 70 },
  { id: "watchlist", priority: 80 },
  { id: "instrumentadmin", priority: 85 },
  { id: "dataadmin", priority: 90 },
  { id: "reports", priority: 100 },
  { id: "settings", priority: 105 },
  { id: "support", priority: 110 },
  { id: "logs", priority: 115 },
  { id: "scenario", priority: 120 },
] as const;
export type TabPlugin = typeof orderedTabPlugins[number];
